version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "daily"
    labels:
      - "npm dependencies"
      - "backend"
  - package-ecosystem: "npm"
    directory: "/front"    schedule:
      interval: "daily"
    labels:
      - "npm dependencies"
      - "frontend"
