version: '3'
services:
  back:
    build:
      context: "./api"
    env_file:
      - ./api/.env
    ports:
      - 80:5000
  front:
    build:
      context: "./front"
    env_file:
      - ./front/.env
    ports:
      - 3000:3000