name: Test API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    strategy:
      matrix:
        node-version: [16]
    steps:
    - uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
        cache-dependency-path: api/yarn.lock
    - name: Install dependencies
      run: yarn install --frozen-lockfile | yarn global add dotenv-cli
    - name: Run tests
      run: yarn run test
